### ISSUE TITLE
Next possible features

### ISSUE THREAD

**Issue by andreymatin** [Frontend-Layers/html-base#20]
- ? disble VSC ext recommendations permanently
- [ ] Browser JS errors to console
- [ ] options.livereload.port, Default: 35729 (+ docker, .env)
- [ ] [concurrently](https://www.npmjs.com/package/concurrently) or [parallelshell](https://www.npmjs.com/package/parallelshell) integration for node process 
- [ ] base64 encoding automation. Ref example: https://base64.guru/converter/encode/image
- [ ] https (https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener)

- [ ] node proxy page config
- [ ] blank command to remove test files
- [ ] JS mode (UMD, ES libs)
- [ ] JS mode (Additional test cases)
- [ ] JS mode (auto project name replace for roll, remove proxy, page-preview)
- [ ] Free templates/examples
- [ ] enable / disable build on fly
- [ ] build check recreation after remove
- [ ] local fonts snippet
- [ ] internal assets compiler
- [ ] Design system generator
- [ ] js modules config - index.js copy
- [ ] add tpl library
- [ ] JS template library for JS HTML resources (maybe with template literals support)
? php support
? google closure integration

-   snippet for background-image: image-set and hight ratio

```css
  background-image: image-set(url('../images/bg.webp') 1x,
      url('../images/bg.webp') 2x);


@media (-webkit-min-device-pixel-ratio: 2),
(min-resolution: 192dpi) {
  .class-name {
    background-image: url('../images/page-bg@2x.jpg');
    background-image: image-set(url('../images/bg.webp') 1x,
      url('../images/bg.webp') 2x);
  }
}

```

- [ ] gulp plugin for https://bitsofco.de/pa11y/
- [x] pnpm simlinks off
- [x] Bootstrap Grid System 5
- [x] CSS Audit/Analyze
- [x] enable / disable purify
- [x] ? AVIF support (https://www.npmjs.com/package/gulp-avif)
- [x] rollup noicy warnings
- sassdoc (http://sassdoc.com/gulp/)
- Test: [css analyzer ](https://www.npmjs.com/package/gulp-analyze-css)
- [x] add ui-explorer
